### ISSUE TITLE
Error on Prayer Times 

### ISSUE THREAD

**Issue by aziziqbal** [metinkale38/namaz-vakti-android#30]
Assalamualaikum.
Hello I am Muslim from Indonesia, I really like your app. I hope you can fix this error. Forced Close when i click floating action button on Prayer Times. Can you fix this?

 FATAL EXCEPTION: pool-4-thread-2
                                                                        java.lang.NullPointerException
                                                                            at com.metinkale.prayerapp.vakit.times.Cities.closeDatabase(Cities.java:153)
                                                                            at com.metinkale.prayerapp.vakit.times.Cities.search2(Cities.java:397)
                                                                            at com.metinkale.prayerapp.vakit.times.Cities.search(Cities.java:271)
                                                                            at com.metinkale.prayerapp.vakit.times.Cities$4.run(Cities.java:127)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                            at java.lang.Thread.run(Thread.java:838)

**Comment by metinkale38** [comment]
did you copy the assets into your project?

**Comment by aziziqbal** [comment]
Sorry I forget Thanks metinkale
